
# プラグイン設定
general:
  # タイムゾーンを選択します。日付や時刻を扱う設定に適用されます。
  timezone: Asia/Tokyo  # or local

# イベント開始設定
event-start:
  # いずれかの条件を満たすと実行
  conditions:
    - type: real-clock
      time-hours: 22
      time-minutes: 30

  # 開始前通知
  pre-notify:
    enable: true
    minutes: 3

  # 開始時にLandスポーン地点、または敷地内のランダムな位置にテレポートします
  teleport-to-land: true

  # 開始アクション
  actions:
    player:
      effects:
        blindness:
          duration: 40
          silent: true
      title:
        text: ""
        subtext: "&4&lまた奴らがやってくる"
        fade-in: 10
        fade-out: 10
        duration: 60

# 襲撃設定
raid:
  # Land未所属プレイヤーを退出または参加させない設定
  non-members-kick-enable: true
  # ゲーム時間
  event-time-minutes: 30
  # ウェーブ数
  waves: 5
  # ウェーブの最大時間。現ウェーブの敵を全て倒すか、この時間が経過すると次のウェーブに移行します (0 以下で無効)
  max-wave-time-minutes: 6
  # ボスバー表示設定
  bossbar:
    # 襲撃イベントの進行状況をボスバーに表示します
    enable: true
    color: purple  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarColor.html
    style: solid  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/boss/BarStyle.html
    # 仕様できる値: %wave%, %max_waves%, %enemies%, %total_enemies%, %tickets%, %land%
    text: "&6Wave: %wave%/%max_waves% &f| &c敵残存数: %enemies% &f| &e残りチケット: %tickets%"
  # 死亡回数の制限。このカウントが 0 になるとイベント終了(敗北)します (0 以下で無効)
  tickets: 20
  # イベント中に付与する権限グループ
  luckperms-group: in-raidspawner
  # 襲撃イベントを発生させるワールド (nullでLandのスポーン設定を使用)
  world:
  # スポーン位置: Landから離すチャンク数
  mobs-distance-chunks: 2
  # モブに発光効果を付与する敵残存数
  mobs-glowing-enemies: 10

  # モブ設定のグループ条件タイプ (省略してall)
  # - all  条件を満たすグループを全て
  # - one  条件を満たす最初のグループ
  mobs-condition-type: "all"
  # モブ設定
  # ※ 式で使用できる値:
  #   - online_players  現在のオンライン人数
  #   - offline_players 現在のオフライン人数
  #   - land_players    Landの全人数
  #   - land_chunks     Landの所有チャンク数
  #   - wave            現在のウェーブ数
  #   - index           現在のセクションの番号
  #   - count           現在のセクションの親の count 値
  mobs:
      # このグループが適用される条件式 (省略して常に有効)
    - condition: "1"
      # スポーン数を数値またはプレイヤー人数などを元に算出する式で適用します (省略して現在のcount値を適用)
      count: "ceil( land_players * (3 + land_chunks * 1.5) * (1 + 0.1 * wave) )"  # or number value
      # スポーン対象を定義します
      enemies:
        - source: mythicmobs
          type: MOB_TYPE
          level: 1
          priority: 1
      # 子グループの条件タイプ (省略してone)
      # - all  条件を満たすグループを全て
      # - one  条件を満たす最初のグループ
      children-condition-type: "one"
      # 条件に基づいて選択するモブグループを切り替えます (省略可)
      # いずれにもマッチしない場合は最後の条件が有効として適用します
      children:
          # このグループが適用される条件式 (省略して常に有効)
        - condition: "count <= 50"
          # スポーン数を数値またはプレイヤー人数などを元に算出する式で適用します (省略して現在のcount値を適用)
          count: null
          # スポーン対象を上書きできます (省略して親enemiesを適用)
          enemies: null
          # 条件に基づいて選択するモブを切り替えます (省略可)
          children: []

        - condition: "count <= 150"
          count: "count / 3"
          enemies:
            - source: mythicmobs
              type: MOB_TYPE
              level: 2
              priority: 1
          children: []

# 成功報酬設定
event-win-rewards:
  # 条件を満たしたもののみ実行
  conditions:
    - type: timer
      time-minutes: 15
      actions:
        player:
          add-money: 3000
        land:

  # どの条件も満たされていない場合のアクション
  condition-else:
    actions:
      player:
        add-money: 5
      land:

# 失敗報酬設定
event-lose-rewards:
  actions:
    player:
    land:
      remove-chunk: 1

# イベント終了設定
event-end:
  send-result-to-discord: true


# Discord連携設定
discord:
  # 連携機能の有効 (DiscordSRVが必要です)
  enable: false
  # 通知を送信するチャンネルID
  channel: 000000000000000000
