name: RaidSpawner
version: '${version}'
main: com.gmail.necnionch.myplugin.raidspawner.bukkit.RaidSpawnerPlugin
api-version: '1.17'
author: Necnion8

depend:
  - Lands

softdepend:
  - Vault
  - MythicMobs
  - PlaceholderAPI
  - LuckPerms

commands:
  raidspawner: {}

permissions:
  raidspawner.admin:
    default: op
    children:
      - raidspawner.bypass.non-members-kick

  raidspawner.bypass.non-members-kick:
    description: "未所属プレイヤーが襲撃イベント中に参加できるようにする権限"
