name: RaidSpawner
version: '${version}'
main: com.gmail.necnionch.myplugin.raidspawner.bukkit.RaidSpawnerPlugin
api-version: '1.17'
author: Necnion8
website: "https://github.com/Necnion8/RaidSpawner"

depend:
  - Lands

softdepend:
  - Vault
  - MythicMobs
  - PlaceholderAPI
  - LuckPerms
  - DiscordSRV
  - StatBadge

commands:
  raidspawner:
    aliases: [rspa]
    permission: raidspawner.command.raidspawner

permissions:
  raidspawner.command.raidspawner: {}
  raidspawner.bypass.non-members-kick:
    description: "未所属プレイヤーが襲撃イベント中に参加できるようにする権限"

  raidspawner.admin:
    default: op
    children:
      - raidspawner.command.raidspawner
      - raidspawner.bypass.non-members-kick
